version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: 'autoprefixer'
        versions:
          - '>= 10.0.0'
      - dependency-name: 'postcss-modules'
        versions:
          - '>= 4.0.0'
      - dependency-name: 'sass-loader'
        versions:
          - '>= 11.0.0'
      - dependency-name: 'webpack'
        versions:
          - '>= 5.0.0'
