version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10

  - package-ecosystem: 'npm'
    directory: '/examples/html-css'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/examples/html-css-js'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/examples/html-css-js-parcel'
    schedule:
      interval: 'weekly'
