version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    default_labels:
      - 'dependencies'
      - 'javascript'
    ignored_updates:
      - match:
          dependency_name: 'webpack'
          version_requirement: '5.x'
