#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2 # <none> (git commit) | message (git commit -m <msg>) | template | merge | squash | commit
# SHA1=$3

if [ "$COMMIT_SOURCE" = "" ]; then
  exec < /dev/tty && yarn cz --hook || true
fi
