name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # required by JamesIves/github-pages-deploy-action

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        env:
          STORYBOOK_MODE: production
          STORYBOOK_GA_ID: ${{ secrets.STORYBOOK_GA_ID }}
        run: |
          yarn generate
          npx build-storybook -o public

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
          SINGLE_COMMIT: true
