name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2.3.4
      - run: git fetch origin main # needed for commitlint

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Run commitlint
        if: github.actor != 'dependabot[bot]' # allow long commit message body
        run: yarn lint:commit

      - name: Run stylelint
        run: yarn lint:style

      - name: Run ESLint
        run: yarn lint:es

      - name: Run tsc (type check)
        run: yarn lint:ts

      - name: Run Prettier
        run: yarn lint:prettier
